export type SeedRoom = {
  id: string;
  type: string;
  bedType: string;
  bedCount: number;
  maxOccupancy: number;
  squareFootage: number;
  pricePerNight: number;
  amenities: string[];
  availableDates: string[];
};

export type SeedHotel = {
  id: string;
  name: string;
  description: string;
  starRating: number;
  overallRating: number;
  reviewCount: number;
  address: {
    street: string;
    city: string;
    state: string;
    zipCode: string;
    country: string;
  };
  contact: {
    phone: string;
    email: string;
  };
  amenities: string[];
  policies: {
    checkInTime: string;
    checkOutTime: string;
    cancellation: string;
  };
  rooms: SeedRoom[];
};

export const seedHotels = [
  {
    id: 'hotel-01',
    name: 'The Grand Luminary',
    description:
      'A luxury oasis in the heart of downtown, featuring panoramic city views, world-class dining, and a serene rooftop escape.',
    starRating: 5,
    overallRating: 4.8,
    reviewCount: 1240,
    address: {
      street: '789 Skyline Blvd',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60611',
      country: 'USA',
    },
    contact: {
      phone: '+1-312-555-0199',
      email: 'stay@grandluminary.com',
    },
    amenities: [
      'pool',
      'free Wi-Fi',
      'fitness_center',
      'spa',
      'valet_parking',
      'pet_friendly',
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-01a',
        type: 'Deluxe King Room',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 450,
        pricePerNight: 299,
        amenities: ['city_view', 'mini_bar'],
        availableDates: ['2026-07-10', '2026-07-11', '2026-07-12'],
      },
      {
        id: 'room-01b',
        type: 'Standard Queen',
        bedType: 'Queen',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 350,
        pricePerNight: 199,
        amenities: ['courtyard_view'],
        availableDates: ['2026-07-10', '2026-07-11'],
      },
    ],
  },
  {
    id: 'hotel-02',
    name: 'The Chicago Riverfront Inn',
    description:
      'Towering corporate-friendly hotel located in the loop with dynamic architectural views and modern workstations.',
    starRating: 4,
    overallRating: 4.3,
    reviewCount: 1410,
    address: {
      street: '320 N Dearborn St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60654',
      country: 'USA',
    },
    contact: {
      phone: '+1-312-555-0145',
      email: 'reservations@chicagoriverfront.com',
    },
    amenities: [
      'pool',
      'free Wi-Fi',
      'fitness_center',
      'restaurant',
      'valet_parking',
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '12:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-02a',
        type: 'Standard Double Queen',
        bedType: 'Queen',
        bedCount: 2,
        maxOccupancy: 4,
        squareFootage: 380,
        pricePerNight: 175,
        amenities: ['river_view'],
        availableDates: ['2026-07-10', '2026-07-11', '2026-07-12'],
      },
    ],
  },
  {
    id: 'hotel-03',
    name: 'Windy City Suites',
    description:
      'Modern urban suites designed for extended stays, offering fully equipped kitchenettes and an unbeatable central location.',
    starRating: 3,
    overallRating: 4.1,
    reviewCount: 520,
    address: {
      street: '55 E Ontario St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60611',
      country: 'USA',
    },
    contact: {
      phone: '+1-312-555-0188',
      email: 'info@windycitysuites.com',
    },
    amenities: [
      'free Wi-Fi',
      'fitness_center',
      'laundry_service',
      'pet_friendly',
    ],
    policies: {
      checkInTime: '16:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 48 hours before check-in',
    },
    rooms: [
      {
        id: 'room-03a',
        type: 'Studio King Suite',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 410,
        pricePerNight: 135,
        amenities: ['kitchenette', 'smart_tv'],
        availableDates: ['2026-07-11', '2026-07-12', '2026-07-13'],
      },
    ],
  },
  {
    id: 'hotel-04',
    name: 'Magnolia Place Chicago',
    description:
      'A charming, boutique-style historic building reimagined with contemporary comforts and neighborhood vibes.',
    starRating: 3,
    overallRating: 4.5,
    reviewCount: 295,
    address: {
      street: '1420 N Lincoln Ave',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60614',
      country: 'USA',
    },
    contact: {
      phone: '+1-312-555-0121',
      email: 'welcome@magnoliaplacechi.com',
    },
    amenities: ['free Wi-Fi', 'free_breakfast', 'bicycle_rentals'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellation: 'Non-refundable booking',
    },
    rooms: [
      {
        id: 'room-04a',
        type: 'Standard Queen',
        bedType: 'Queen',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 300,
        pricePerNight: 115,
        amenities: ['garden_view'],
        availableDates: [],
      },
    ],
  },
  {
    id: 'hotel-05',
    name: 'Urban Nest Boutique Hotel',
    description:
      'A trendy, eco-friendly boutique hotel nestled in a vibrant arts district. Walking distance to local breweries and cafes.',
    starRating: 4,
    overallRating: 4.5,
    reviewCount: 612,
    address: {
      street: '412 Canary Way',
      city: 'Austin',
      state: 'TX',
      zipCode: '78701',
      country: 'USA',
    },
    contact: {
      phone: '+1-512-555-0143',
      email: 'hello@urbannestaustin.com',
    },
    amenities: [
      'free Wi-Fi',
      'fitness_center',
      'bicycle_rentals',
      'pet_friendly',
    ],
    policies: {
      checkInTime: '16:00',
      checkOutTime: '12:00',
      cancellation: 'Non-refundable booking',
    },
    rooms: [
      {
        id: 'room-05a',
        type: 'Standard Queen',
        bedType: 'Queen',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 310,
        pricePerNight: 145,
        amenities: ['smart_tv'],
        availableDates: ['2026-07-12', '2026-07-13', '2026-07-14'],
      },
      {
        id: 'room-05b',
        type: 'Double Queen Suite',
        bedType: 'Queen',
        bedCount: 2,
        maxOccupancy: 4,
        squareFootage: 520,
        pricePerNight: 210,
        amenities: ['kitchenette'],
        availableDates: ['2026-07-13', '2026-07-14'],
      },
    ],
  },
  {
    id: 'hotel-06',
    name: 'Keep Austin Weird Inn',
    description:
      'Embrace the local culture with vibrant murals, vintage decor, and a live acoustic music stage in the lobby.',
    starRating: 2,
    overallRating: 4.2,
    reviewCount: 410,
    address: {
      street: '1503 S Congress Ave',
      city: 'Austin',
      state: 'TX',
      zipCode: '78704',
      country: 'USA',
    },
    contact: {
      phone: '+1-512-555-0187',
      email: 'stay@keepaustinweirdinn.com',
    },
    amenities: ['pool', 'free Wi-Fi', 'free_parking', 'pet_friendly'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-06a',
        type: 'Retro Double Bed',
        bedType: 'Full',
        bedCount: 2,
        maxOccupancy: 4,
        squareFootage: 290,
        pricePerNight: 95,
        amenities: ['mini_fridge'],
        availableDates: ['2026-07-10', '2026-07-11', '2026-07-12'],
      },
    ],
  },
  {
    id: 'hotel-07',
    name: 'Lone Star Luxury Resort',
    description:
      'An expansive premium hill-country estate featuring championship golf courses, cascading pools, and full spa amenities.',
    starRating: 5,
    overallRating: 4.9,
    reviewCount: 890,
    address: {
      street: '9201 Loop 360 N',
      city: 'Austin',
      state: 'TX',
      zipCode: '78730',
      country: 'USA',
    },
    contact: {
      phone: '+1-512-555-0900',
      email: 'reservations@lonestarluxury.com',
    },
    amenities: [
      'pool',
      'free Wi-Fi',
      'spa',
      'fitness_center',
      'valet_parking',
      'restaurant',
    ],
    policies: {
      checkInTime: '16:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 7 days before check-in',
    },
    rooms: [
      {
        id: 'room-07a',
        type: 'Hill Country King Villa',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 680,
        pricePerNight: 450,
        amenities: ['balcony', 'fireplace', 'espresso_machine'],
        availableDates: [
          '2026-07-10',
          '2026-07-11',
          '2026-07-12',
          '2026-07-13',
        ],
      },
    ],
  },
  {
    id: 'hotel-08',
    name: 'ATX Urban Stay',
    description:
      'Sleek, minimalist downtown high-rise catering heavily to modern business travelers and digital nomads.',
    starRating: 4,
    overallRating: 4.4,
    reviewCount: 315,
    address: {
      street: '208 E 7th St',
      city: 'Austin',
      state: 'TX',
      zipCode: '78701',
      country: 'USA',
    },
    contact: {
      phone: '+1-512-555-0112',
      email: 'desk@atxurbanstay.com',
    },
    amenities: ['free Wi-Fi', 'fitness_center', 'meeting_rooms'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-08a',
        type: 'Executive King',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 360,
        pricePerNight: 185,
        amenities: ['work_desk', 'smart_tv'],
        availableDates: ['2026-07-11', '2026-07-12', '2026-07-13'],
      },
    ],
  },
  {
    id: 'hotel-09',
    name: 'Sunset Coastal Inn',
    description:
      'A budget-friendly, relaxed roadside inn located just minutes away from the public beach boardwalk.',
    starRating: 2,
    overallRating: 3.9,
    reviewCount: 185,
    address: {
      street: '102 Ocean Drive',
      city: 'Miami',
      state: 'FL',
      zipCode: '33139',
      country: 'USA',
    },
    contact: {
      phone: '+1-305-555-0111',
      email: 'frontdesk@sunsetcoastalinn.com',
    },
    amenities: ['pool', 'free Wi-Fi', 'free_parking'],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '10:00',
      cancellation: 'Free cancellation up to 48 hours before check-in',
    },
    rooms: [
      {
        id: 'room-09a',
        type: 'Standard Queen',
        bedType: 'Queen',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 280,
        pricePerNight: 85,
        amenities: ['mini_fridge', 'microwave'],
        availableDates: ['2026-07-10', '2026-07-11', '2026-07-12'],
      },
    ],
  },
  {
    id: 'hotel-10',
    name: 'Neon Palms Motel',
    description:
      'A stylishly retro-renovated 1950s roadside motel providing vibrant pastel colors and a classic pool scene.',
    starRating: 2,
    overallRating: 4,
    reviewCount: 145,
    address: {
      street: '2200 Biscayne Blvd',
      city: 'Miami',
      state: 'FL',
      zipCode: '33137',
      country: 'USA',
    },
    contact: {
      phone: '+1-305-555-0176',
      email: 'hello@neonpalmsmiami.com',
    },
    amenities: ['pool', 'free Wi-Fi', 'free_parking'],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '11:00',
      cancellation: 'Non-refundable booking',
    },
    rooms: [
      {
        id: 'room-10a',
        type: 'Retro Queen',
        bedType: 'Queen',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 260,
        pricePerNight: 95,
        amenities: ['mini_fridge'],
        availableDates: [],
      },
    ],
  },
  {
    id: 'hotel-11',
    name: 'South Beach Sanctum',
    description:
      'Art Deco masterpiece right on the waterfront, prioritizing intimate luxury, curated cocktail lounges, and private beach loungers.',
    starRating: 5,
    overallRating: 4.7,
    reviewCount: 920,
    address: {
      street: '1301 Ocean Ave',
      city: 'Miami',
      state: 'FL',
      zipCode: '33139',
      country: 'USA',
    },
    contact: {
      phone: '+1-305-555-0999',
      email: 'concierge@sosanctum.com',
    },
    amenities: ['pool', 'free Wi-Fi', 'beach_access', 'spa', 'valet_parking'],
    policies: {
      checkInTime: '16:00',
      checkOutTime: '12:00',
      cancellation: 'Free cancellation up to 72 hours before check-in',
    },
    rooms: [
      {
        id: 'room-11a',
        type: 'Oceanfront Ocean King',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 510,
        pricePerNight: 399,
        amenities: ['ocean_view', 'balcony'],
        availableDates: [
          '2026-07-10',
          '2026-07-11',
          '2026-07-12',
          '2026-07-13',
        ],
      },
    ],
  },
  {
    id: 'hotel-12',
    name: 'Biscayne Bay Resort',
    description:
      'An action-packed family resort boasting an on-site marina, water sports center, and panoramic views of the bay skyline.',
    starRating: 4,
    overallRating: 4.4,
    reviewCount: 1150,
    address: {
      street: '1601 N Bayshore Dr',
      city: 'Miami',
      state: 'FL',
      zipCode: '33132',
      country: 'USA',
    },
    contact: {
      phone: '+1-305-555-0155',
      email: 'fun@biscaynebayresort.com',
    },
    amenities: [
      'pool',
      'free Wi-Fi',
      'fitness_center',
      'restaurant',
      'marina_access',
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-12a',
        type: 'Bay View Double Queen',
        bedType: 'Queen',
        bedCount: 2,
        maxOccupancy: 4,
        squareFootage: 420,
        pricePerNight: 220,
        amenities: ['water_view', 'mini_fridge'],
        availableDates: ['2026-07-11', '2026-07-12', '2026-07-13'],
      },
    ],
  },
  {
    id: 'hotel-13',
    name: 'The Hudson Neo',
    description:
      'Sleek industrial chic in Manhattan. Micro-rooms optimized for urban explorers and business travelers alike.',
    starRating: 4,
    overallRating: 4.2,
    reviewCount: 905,
    address: {
      street: '550 W 42nd St',
      city: 'New York',
      state: 'NY',
      zipCode: '10036',
      country: 'USA',
    },
    contact: {
      phone: '+1-212-555-0988',
      email: 'stay@hudsonneo.com',
    },
    amenities: ['free Wi-Fi', 'fitness_center', 'rooftop_bar'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-13a',
        type: 'Micro King',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 220,
        pricePerNight: 180,
        amenities: ['city_view'],
        availableDates: ['2026-07-10', '2026-07-11', '2026-07-12'],
      },
    ],
  },
  {
    id: 'hotel-14',
    name: 'Manhattan Heights Hotel',
    description:
      'A historic, soaring architectural landmark offering majestic grandeur and world-class concierges near Midtown.',
    starRating: 5,
    overallRating: 4.6,
    reviewCount: 2100,
    address: {
      street: '301 Park Ave',
      city: 'New York',
      state: 'NY',
      zipCode: '10022',
      country: 'USA',
    },
    contact: {
      phone: '+1-212-555-0100',
      email: 'reservations@manhattanheights.com',
    },
    amenities: [
      'free Wi-Fi',
      'fitness_center',
      'spa',
      'valet_parking',
      'restaurant',
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '12:00',
      cancellation: 'Free cancellation up to 48 hours before check-in',
    },
    rooms: [
      {
        id: 'room-14a',
        type: 'Premier King Suite',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 550,
        pricePerNight: 495,
        amenities: ['soaking_tub', 'mini_bar'],
        availableDates: [
          '2026-07-10',
          '2026-07-11',
          '2026-07-12',
          '2026-07-13',
        ],
      },
    ],
  },
  {
    id: 'hotel-15',
    name: 'Central Park View Inn',
    description:
      'Cozy, classic boutique establishment proudly situated right along Central Park South with spectacular foliage lookouts.',
    starRating: 3,
    overallRating: 4.3,
    reviewCount: 480,
    address: {
      street: '120 Central Park S',
      city: 'New York',
      state: 'NY',
      zipCode: '10019',
      country: 'USA',
    },
    contact: {
      phone: '+1-212-555-0156',
      email: 'info@cpviewinn.com',
    },
    amenities: ['free Wi-Fi', 'free_breakfast', 'pet_friendly'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-15a',
        type: 'Park View Queen',
        bedType: 'Queen',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 290,
        pricePerNight: 210,
        amenities: ['park_view'],
        availableDates: ['2026-07-11', '2026-07-12', '2026-07-13'],
      },
    ],
  },
  {
    id: 'hotel-16',
    name: 'Brooklyn Brick Hotel',
    description:
      'Converted historic warehouse in Williamsburg exposing beautiful industrial brick, timber beams, and creative craft spaces.',
    starRating: 4,
    overallRating: 4.5,
    reviewCount: 680,
    address: {
      street: '85 Wythe Ave',
      city: 'New York',
      state: 'NY',
      zipCode: '11249',
      country: 'USA',
    },
    contact: {
      phone: '+1-718-555-0144',
      email: 'stay@brooklynbrick.com',
    },
    amenities: ['free Wi-Fi', 'fitness_center', 'rooftop_bar', 'pet_friendly'],
    policies: {
      checkInTime: '16:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 48 hours before check-in',
    },
    rooms: [
      {
        id: 'room-16a',
        type: 'Loft Double Queen',
        bedType: 'Queen',
        bedCount: 2,
        maxOccupancy: 4,
        squareFootage: 450,
        pricePerNight: 265,
        amenities: ['skyline_view'],
        availableDates: ['2026-07-10', '2026-07-11', '2026-07-12'],
      },
    ],
  },
  {
    id: 'hotel-17',
    name: 'Pacific Crest Lodge',
    description:
      'A rustic timber lodge featuring cozy fireplaces and direct trail access near the scenic foothills.',
    starRating: 3,
    overallRating: 4.6,
    reviewCount: 340,
    address: {
      street: '1200 Mountain Highway',
      city: 'Seattle',
      state: 'WA',
      zipCode: '98101',
      country: 'USA',
    },
    contact: {
      phone: '+1-206-555-0122',
      email: 'info@pacificcrestseattle.com',
    },
    amenities: ['free Wi-Fi', 'free_parking', 'hot_tub', 'pet_friendly'],
    policies: {
      checkInTime: '16:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 7 days before check-in',
    },
    rooms: [
      {
        id: 'room-17a',
        type: 'Fireplace Suite',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 400,
        pricePerNight: 165,
        amenities: ['fireplace', 'balcony'],
        availableDates: [],
      },
    ],
  },
  {
    id: 'hotel-18',
    name: 'Emerald City Suites',
    description:
      'Modern downtown high-rise accommodations utilizing tech-integrated rooms, voice controls, and automated concierges.',
    starRating: 4,
    overallRating: 4.2,
    reviewCount: 510,
    address: {
      street: '801 Pike St',
      city: 'Seattle',
      state: 'WA',
      zipCode: '98101',
      country: 'USA',
    },
    contact: {
      phone: '+1-206-555-0155',
      email: 'hello@emeraldcitysuites.com',
    },
    amenities: ['free Wi-Fi', 'fitness_center', 'meeting_rooms'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-18a',
        type: 'Standard King',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 310,
        pricePerNight: 140,
        amenities: ['smart_tv'],
        availableDates: ['2026-07-10', '2026-07-11', '2026-07-12'],
      },
    ],
  },
  {
    id: 'hotel-19',
    name: 'Puget Sound Vista',
    description:
      'Stunning luxury spaces overlooking the historical Pike Place Market and the sweeping waters of the sound.',
    starRating: 5,
    overallRating: 4.8,
    reviewCount: 1050,
    address: {
      street: '1021 1st Ave',
      city: 'Seattle',
      state: 'WA',
      zipCode: '98104',
      country: 'USA',
    },
    contact: {
      phone: '+1-206-555-0199',
      email: 'stay@pugetsoundvista.com',
    },
    amenities: ['pool', 'free Wi-Fi', 'fitness_center', 'spa', 'valet_parking'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '12:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-19a',
        type: 'Waterfront Premier King',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 480,
        pricePerNight: 315,
        amenities: ['water_view', 'espresso_machine'],
        availableDates: [
          '2026-07-10',
          '2026-07-11',
          '2026-07-12',
          '2026-07-13',
        ],
      },
    ],
  },
  {
    id: 'hotel-20',
    name: 'Rain City Boutique',
    description:
      'An artsy, indie escape in Capitol Hill displaying massive vinyl record collections, library walls, and locally roasted coffee.',
    starRating: 3,
    overallRating: 4.5,
    reviewCount: 275,
    address: {
      street: '1112 E Pine St',
      city: 'Seattle',
      state: 'WA',
      zipCode: '98122',
      country: 'USA',
    },
    contact: {
      phone: '+1-206-555-0143',
      email: 'frontdesk@raincityboutique.com',
    },
    amenities: [
      'free Wi-Fi',
      'free_breakfast',
      'bicycle_rentals',
      'pet_friendly',
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 48 hours before check-in',
    },
    rooms: [
      {
        id: 'room-20a',
        type: 'Standard Queen Loft',
        bedType: 'Queen',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 330,
        pricePerNight: 125,
        amenities: ['record_player'],
        availableDates: ['2026-07-10', '2026-07-11', '2026-07-12'],
      },
    ],
  },
  {
    id: 'hotel-21',
    name: 'The Piccadilly Crown',
    description:
      'A quintessential British luxury hotel combining timeless Edwardian elegance with modern West End sophistication.',
    starRating: 5,
    overallRating: 4.9,
    reviewCount: 1840,
    address: {
      street: '45 Piccadilly',
      city: 'London',
      state: 'Greater London',
      zipCode: 'W1J 0LP',
      country: 'United Kingdom',
    },
    contact: {
      phone: '+44-20-7555-0143',
      email: 'concierge@piccadillycrown.co.uk',
    },
    amenities: [
      'pool',
      'free Wi-Fi',
      'fitness_center',
      'spa',
      'valet_parking',
      'afternoon_tea_lounge',
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '12:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-21a',
        type: 'Royal King Suite',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 520,
        pricePerNight: 420,
        amenities: ['city_view', 'mini_bar', 'espresso_machine'],
        availableDates: ['2026-07-10', '2026-07-11', '2026-07-12'],
      },
    ],
  },
  {
    id: 'hotel-22',
    name: 'Thames View Apartments',
    description:
      'Sleek, upscale aparthotel right on the South Bank, offering corporate travelers spacious layouts and beautiful river vistas.',
    starRating: 4,
    overallRating: 4.4,
    reviewCount: 620,
    address: {
      street: '210 Albert Embankment',
      city: 'London',
      state: 'Greater London',
      zipCode: 'SE1 7GR',
      country: 'United Kingdom',
    },
    contact: {
      phone: '+44-20-7555-0199',
      email: 'stay@thamesviewapts.co.uk',
    },
    amenities: [
      'free Wi-Fi',
      'fitness_center',
      'laundry_service',
      'meeting_rooms',
    ],
    policies: {
      checkInTime: '16:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 48 hours before check-in',
    },
    rooms: [
      {
        id: 'room-22a',
        type: 'Executive Studio',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 410,
        pricePerNight: 245,
        amenities: ['river_view', 'kitchenette', 'smart_tv'],
        availableDates: [
          '2026-07-10',
          '2026-07-11',
          '2026-07-12',
          '2026-07-13',
        ],
      },
    ],
  },
  {
    id: 'hotel-23',
    name: 'Shoreditch Hip Hotel',
    description:
      'An industrial-chic boutique hotel featuring exposed brick, local artist galleries, and a highly popular rooftop bar.',
    starRating: 3,
    overallRating: 4.6,
    reviewCount: 910,
    address: {
      street: '96 Great Eastern St',
      city: 'London',
      state: 'Greater London',
      zipCode: 'EC2A 3HX',
      country: 'United Kingdom',
    },
    contact: {
      phone: '+44-20-7555-0112',
      email: 'hello@shoreditchhip.co.uk',
    },
    amenities: ['free Wi-Fi', 'rooftop_bar', 'bicycle_rentals', 'pet_friendly'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellation: 'Non-refundable booking',
    },
    rooms: [
      {
        id: 'room-23a',
        type: 'Standard Double',
        bedType: 'Queen',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 280,
        pricePerNight: 160,
        amenities: ['record_player', 'smart_tv'],
        availableDates: ['2026-07-11', '2026-07-12', '2026-07-13'],
      },
    ],
  },
  {
    id: 'hotel-24',
    name: 'The Kensington Tavern Inn',
    description:
      'A charming, budget-friendly traditional inn situated directly above a historic, cozy pub near the museums.',
    starRating: 2,
    overallRating: 4.1,
    reviewCount: 340,
    address: {
      street: '12 Cromwell Rd',
      city: 'London',
      state: 'Greater London',
      zipCode: 'SW7 2HR',
      country: 'United Kingdom',
    },
    contact: {
      phone: '+44-20-7555-0188',
      email: 'rooms@kensingtontavern.co.uk',
    },
    amenities: ['free Wi-Fi', 'free_breakfast', 'on_site_pub'],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '10:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-24a',
        type: 'Standard Twin Room',
        bedType: 'Twin',
        bedCount: 2,
        maxOccupancy: 2,
        squareFootage: 240,
        pricePerNight: 95,
        amenities: ['coffee_maker'],
        availableDates: [],
      },
    ],
  },
  {
    id: 'hotel-25',
    name: 'Le Palace Lumière',
    description:
      'An opulent Parisian landmark offering palatial suites, white-glove service, and direct balconies facing the Eiffel Tower.',
    starRating: 5,
    overallRating: 4.9,
    reviewCount: 1560,
    address: {
      street: '25 Avenue Montaigne',
      city: 'Paris',
      state: 'Île-de-France',
      zipCode: '75008',
      country: 'France',
    },
    contact: {
      phone: '+33-1-5555-0182',
      email: 'lumiere@palaceparis.fr',
    },
    amenities: [
      'pool',
      'free Wi-Fi',
      'spa',
      'fitness_center',
      'valet_parking',
      'michelin_restaurant',
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '12:00',
      cancellation: 'Free cancellation up to 48 hours before check-in',
    },
    rooms: [
      {
        id: 'room-25a',
        type: 'Eiffel View Prestige',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 580,
        pricePerNight: 590,
        amenities: ['eiffel_tower_view', 'balcony', 'mini_bar'],
        availableDates: ['2026-07-10', '2026-07-11', '2026-07-12'],
      },
    ],
  },
  {
    id: 'hotel-26',
    name: 'Marais Chic Boutique',
    description:
      'Artistic, highly fashionable hotel beautifully hidden away inside a historic 17th-century courtyard in Le Marais.',
    starRating: 4,
    overallRating: 4.7,
    reviewCount: 480,
    address: {
      street: '14 Rue des Rosiers',
      city: 'Paris',
      state: 'Île-de-France',
      zipCode: '75004',
      country: 'France',
    },
    contact: {
      phone: '+33-1-5555-0144',
      email: 'stay@maraischic.fr',
    },
    amenities: [
      'free Wi-Fi',
      'fitness_center',
      'bicycle_rentals',
      'courtyard_cafe',
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-26a',
        type: 'Deluxe Double',
        bedType: 'Queen',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 320,
        pricePerNight: 230,
        amenities: ['courtyard_view', 'smart_tv'],
        availableDates: ['2026-07-11', '2026-07-12', '2026-07-13'],
      },
    ],
  },
  {
    id: 'hotel-27',
    name: 'Seine River Vista',
    description:
      'A highly comfortable midscale hotel situated directly on the Left Bank, within easy walking distance to Notre Dame.',
    starRating: 3,
    overallRating: 4.3,
    reviewCount: 835,
    address: {
      street: '56 Quai des Grands Augustins',
      city: 'Paris',
      state: 'Île-de-France',
      zipCode: '75006',
      country: 'France',
    },
    contact: {
      phone: '+33-1-5555-0111',
      email: 'info@seinerivervista.fr',
    },
    amenities: ['free Wi-Fi', 'free_breakfast', 'bar'],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-27a',
        type: 'Standard Queen',
        bedType: 'Queen',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 270,
        pricePerNight: 155,
        amenities: ['river_view'],
        availableDates: ['2026-07-10', '2026-07-11', '2026-07-12'],
      },
    ],
  },
  {
    id: 'hotel-28',
    name: 'Montmartre Retro Hostel',
    description:
      'A budget-friendly, high-energy artistic hostel and hotel hybrid situated on the steep, winding hills of Montmartre.',
    starRating: 2,
    overallRating: 4,
    reviewCount: 510,
    address: {
      street: "82 Rue d'Orsel",
      city: 'Paris',
      state: 'Île-de-France',
      zipCode: '75018',
      country: 'France',
    },
    contact: {
      phone: '+33-1-5555-0155',
      email: 'frontdesk@montmartreretro.fr',
    },
    amenities: ['free Wi-Fi', 'laundry_service', 'social_lounge'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '10:00',
      cancellation: 'Non-refundable booking',
    },
    rooms: [
      {
        id: 'room-28a',
        type: 'Private Micro Double',
        bedType: 'Full',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 190,
        pricePerNight: 85,
        amenities: ['city_view'],
        availableDates: ['2026-07-10', '2026-07-11'],
      },
    ],
  },
  {
    id: 'hotel-29',
    name: 'Shinjuku Sky Tower',
    description:
      'An ultra-modern luxury high-rise towering above Tokyo, featuring an indoor pool on the 45th floor and views of Mount Fuji.',
    starRating: 5,
    overallRating: 4.8,
    reviewCount: 2210,
    address: {
      street: '3-2-1 Nishi-Shinjuku',
      city: 'Tokyo',
      state: 'Tokyo-to',
      zipCode: '160-0023',
      country: 'Japan',
    },
    contact: {
      phone: '+81-3-5555-0191',
      email: 'stay@shinjukuskytower.jp',
    },
    amenities: [
      'pool',
      'free Wi-Fi',
      'fitness_center',
      'spa',
      'valet_parking',
      'sky_bar',
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '12:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-29a',
        type: 'Skyline Executive King',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 480,
        pricePerNight: 410,
        amenities: ['fuji_view', 'deep_soaking_tub'],
        availableDates: [
          '2026-07-10',
          '2026-07-11',
          '2026-07-12',
          '2026-07-13',
        ],
      },
    ],
  },
  {
    id: 'hotel-30',
    name: 'Shibuya Neon Nest',
    description:
      'A tech-forward, high-design boutique hotel catering perfectly to travelers wanting to be steps away from the famous crossing.',
    starRating: 4,
    overallRating: 4.5,
    reviewCount: 1130,
    address: {
      street: '1-22-10 Jinnan',
      city: 'Tokyo',
      state: 'Tokyo-to',
      zipCode: '150-0041',
      country: 'Japan',
    },
    contact: {
      phone: '+81-3-5555-0145',
      email: 'hello@shibuyaneonnest.jp',
    },
    amenities: [
      'free Wi-Fi',
      'fitness_center',
      'restaurant',
      'laundry_service',
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 48 hours before check-in',
    },
    rooms: [
      {
        id: 'room-30a',
        type: 'Superior Double Room',
        bedType: 'Double',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 290,
        pricePerNight: 220,
        amenities: ['city_view', 'smart_tv'],
        availableDates: ['2026-07-12', '2026-07-13', '2026-07-14'],
      },
    ],
  },
  {
    id: 'hotel-31',
    name: 'Akihabara Tech Inn',
    description:
      'Sleek capsule and micro-room hybrid concept optimized for gaming and tech enthusiasts browsing the electric town.',
    starRating: 3,
    overallRating: 4.2,
    reviewCount: 780,
    address: {
      street: '4-4-2 Sotokanda',
      city: 'Tokyo',
      state: 'Tokyo-to',
      zipCode: '101-0021',
      country: 'Japan',
    },
    contact: {
      phone: '+81-3-5555-0122',
      email: 'desk@akihabaratechinn.jp',
    },
    amenities: ['free Wi-Fi', 'gaming_lounge', 'vending_galore'],
    policies: {
      checkInTime: '16:00',
      checkOutTime: '10:00',
      cancellation: 'Non-refundable booking',
    },
    rooms: [
      {
        id: 'room-31a',
        type: 'Premium Micro Pod',
        bedType: 'Twin',
        bedCount: 1,
        maxOccupancy: 1,
        squareFootage: 140,
        pricePerNight: 75,
        amenities: ['smart_tv'],
        availableDates: [],
      },
    ],
  },
  {
    id: 'hotel-32',
    name: 'Asakusa Traditional Ryokan',
    description:
      'An authentic, peaceful inn featuring beautiful tatami mats, paper screens, and a soothing public hinoki wood bath.',
    starRating: 3,
    overallRating: 4.7,
    reviewCount: 450,
    address: {
      street: '2-16-5 Asakusa',
      city: 'Tokyo',
      state: 'Tokyo-to',
      zipCode: '111-0032',
      country: 'Japan',
    },
    contact: {
      phone: '+81-3-5555-0177',
      email: 'welcome@asakusaryokan.jp',
    },
    amenities: [
      'free Wi-Fi',
      'public_hot_spring_bath',
      'traditional_breakfast',
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '10:00',
      cancellation: 'Free cancellation up to 72 hours before check-in',
    },
    rooms: [
      {
        id: 'room-32a',
        type: 'Tatami Futon Room',
        bedType: 'Futon',
        bedCount: 2,
        maxOccupancy: 3,
        squareFootage: 340,
        pricePerNight: 165,
        amenities: ['garden_view'],
        availableDates: ['2026-07-11', '2026-07-12', '2026-07-13'],
      },
    ],
  },
  {
    id: 'hotel-33',
    name: 'The Harbour Horizon',
    description:
      'World-class coastal luxury located directly in Circular Quay, showcasing unobstructed glass views of the Opera House.',
    starRating: 5,
    overallRating: 4.9,
    reviewCount: 1980,
    address: {
      street: '77 George St',
      city: 'Sydney',
      state: 'NSW',
      zipCode: '2000',
      country: 'Australia',
    },
    contact: {
      phone: '+61-2-5555-0131',
      email: 'res@harbourhorizon.com.au',
    },
    amenities: [
      'pool',
      'free Wi-Fi',
      'fitness_center',
      'spa',
      'valet_parking',
      'harbour_restaurant',
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-33a',
        type: 'Opera Opera King',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 500,
        pricePerNight: 440,
        amenities: ['opera_house_view', 'balcony'],
        availableDates: ['2026-07-10', '2026-07-11', '2026-07-12'],
      },
    ],
  },
  {
    id: 'hotel-34',
    name: 'Bondi Beach Pad',
    description:
      'A highly relaxed surf-chic boutique hotel situated just steps away from the golden sands and rolling waves of Bondi.',
    starRating: 4,
    overallRating: 4.6,
    reviewCount: 590,
    address: {
      street: '120 Campbell Parade',
      city: 'Sydney',
      state: 'NSW',
      zipCode: '2026',
      country: 'Australia',
    },
    contact: {
      phone: '+61-2-5555-0198',
      email: 'surf@bondibeachpad.com.au',
    },
    amenities: [
      'pool',
      'free Wi-Fi',
      'beach_access',
      'bicycle_rentals',
      'pet_friendly',
    ],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '10:00',
      cancellation: 'Free cancellation up to 48 hours before check-in',
    },
    rooms: [
      {
        id: 'room-34a',
        type: 'Oceanfront Balcony Double',
        bedType: 'Queen',
        bedCount: 2,
        maxOccupancy: 4,
        squareFootage: 430,
        pricePerNight: 275,
        amenities: ['ocean_view', 'balcony'],
        availableDates: ['2026-07-11', '2026-07-12', '2026-07-13'],
      },
    ],
  },
  {
    id: 'hotel-35',
    name: 'Newtown Urban Stay',
    description:
      'An artistic bohemian hotel celebrating local coffee roasters, vinyl collections, and the bustling inner-west restaurant scene.',
    starRating: 3,
    overallRating: 4.4,
    reviewCount: 310,
    address: {
      street: '294 King St',
      city: 'Sydney',
      state: 'NSW',
      zipCode: '2042',
      country: 'Australia',
    },
    contact: {
      phone: '+61-2-5555-0156',
      email: 'frontdesk@newtownurban.com.au',
    },
    amenities: ['free Wi-Fi', 'courtyard_lounge', 'pet_friendly'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-35a',
        type: 'Standard Queen',
        bedType: 'Queen',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 310,
        pricePerNight: 145,
        amenities: ['smart_tv'],
        availableDates: ['2026-07-10', '2026-07-11', '2026-07-12'],
      },
    ],
  },
  {
    id: 'hotel-36',
    name: 'Circular Quay Express',
    description:
      'A functional, no-frills, highly localized business-focused hotel optimized for transit and exploring the harbor hubs.',
    starRating: 3,
    overallRating: 4.1,
    reviewCount: 740,
    address: {
      street: '15 Pitt St',
      city: 'Sydney',
      state: 'NSW',
      zipCode: '2000',
      country: 'Australia',
    },
    contact: {
      phone: '+61-2-5555-0104',
      email: 'info@cqexpress.com.au',
    },
    amenities: ['free Wi-Fi', 'fitness_center', 'meeting_rooms'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '11:00',
      cancellation: 'Non-refundable booking',
    },
    rooms: [
      {
        id: 'room-36a',
        type: 'Standard King',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 280,
        pricePerNight: 130,
        amenities: ['work_desk'],
        availableDates: [],
      },
    ],
  },
  {
    id: 'hotel-37',
    name: 'Villa Borghese Imperial',
    description:
      'A breathtaking historic Renaissance palace restored into an elite, world-class resort overlooking lush Italian private gardens.',
    starRating: 5,
    overallRating: 4.9,
    reviewCount: 1105,
    address: {
      street: '12 Via Veneto',
      city: 'Rome',
      state: 'Lazio',
      zipCode: '00187',
      country: 'Italy',
    },
    contact: {
      phone: '+39-06-5555-0176',
      email: 'imperial@villaborghese.it',
    },
    amenities: [
      'pool',
      'free Wi-Fi',
      'spa',
      'fitness_center',
      'valet_parking',
      'fine_dining_terrace',
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '12:00',
      cancellation: 'Free cancellation up to 48 hours before check-in',
    },
    rooms: [
      {
        id: 'room-37a',
        type: 'Grand Heritage Suite',
        bedType: 'King',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 610,
        pricePerNight: 510,
        amenities: ['fresco_ceilings', 'garden_view'],
        availableDates: ['2026-07-10', '2026-07-11', '2026-07-12'],
      },
    ],
  },
  {
    id: 'hotel-38',
    name: 'Trastevere Charm Boutique',
    description:
      'An Ivy-draped, romantic boutique escape tucked away safely in the winding, cobblestone alleyways of Trastevere.',
    starRating: 4,
    overallRating: 4.7,
    reviewCount: 650,
    address: {
      street: '45 Via della Lungaretta',
      city: 'Rome',
      state: 'Lazio',
      zipCode: '00153',
      country: 'Italy',
    },
    contact: {
      phone: '+39-06-5555-0110',
      email: 'stay@trasteverecharm.it',
    },
    amenities: [
      'free Wi-Fi',
      'free_breakfast',
      'rooftop_wine_bar',
      'bicycle_rentals',
    ],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '11:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-38a',
        type: 'Deluxe Double',
        bedType: 'Queen',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 340,
        pricePerNight: 210,
        amenities: ['terrace_access', 'smart_tv'],
        availableDates: ['2026-07-11', '2026-07-12', '2026-07-13'],
      },
    ],
  },
  {
    id: 'hotel-39',
    name: 'Colosseum Heritage Inn',
    description:
      'Comfortable midscale accommodations with a majestic rooftop terrace providing sweeping lookouts directly over the Colosseum arches.',
    starRating: 3,
    overallRating: 4.4,
    reviewCount: 920,
    address: {
      street: '8 Via dei Fori Imperiali',
      city: 'Rome',
      state: 'Lazio',
      zipCode: '00184',
      country: 'Italy',
    },
    contact: {
      phone: '+39-06-5555-0166',
      email: 'info@colosseumheritage.it',
    },
    amenities: ['free Wi-Fi', 'rooftop_terrace', 'bar'],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '10:00',
      cancellation: 'Free cancellation up to 24 hours before check-in',
    },
    rooms: [
      {
        id: 'room-39a',
        type: 'Standard Queen',
        bedType: 'Queen',
        bedCount: 1,
        maxOccupancy: 2,
        squareFootage: 290,
        pricePerNight: 165,
        amenities: ['ruins_view'],
        availableDates: ['2026-07-10', '2026-07-11', '2026-07-12'],
      },
    ],
  },
  {
    id: 'hotel-40',
    name: 'Roma Termini Rooms',
    description:
      'Clean, hyper-affordable micro-hotel setup located adjacent to the central station, geared directly toward budget rail travelers.',
    starRating: 2,
    overallRating: 3.9,
    reviewCount: 415,
    address: {
      street: '142 Via Marsala',
      city: 'Rome',
      state: 'Lazio',
      zipCode: '00185',
      country: 'Italy',
    },
    contact: {
      phone: '+39-06-5555-0143',
      email: 'desk@romaterminirooms.it',
    },
    amenities: ['free Wi-Fi', 'luggage_storage'],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '10:00',
      cancellation: 'Non-refundable booking',
    },
    rooms: [
      {
        id: 'room-40a',
        type: 'Basic Twin Room',
        bedType: 'Twin',
        bedCount: 2,
        maxOccupancy: 2,
        squareFootage: 210,
        pricePerNight: 80,
        amenities: ['mini_fridge'],
        availableDates: ['2026-07-10', '2026-07-11'],
      },
    ],
  },
] satisfies SeedHotel[];
